management:
  context-path: /management
spring:
  application:
    name: abxtract
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show_sql: false
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/abxtract
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
google:
  oauth2:
    id: 130476430955-mpuj4grf05tl2gq2f73g4p8liqc45blp.apps.googleusercontent.com
    secret: ng1zI-i9LkXx7i6T9zh3tV-P
    callback: http://localhost:8080/auth/callback


