management:
  context-path: /management
spring:
  application:
    name: abxtract
    domain: localhost
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show_sql: true
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/abxtract
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
google:
  oauth2:
    id: 46724653377-5mc933uc6sk2525j3dj2i92ph347udmt.apps.googleusercontent.com
    secret: hIJbL1V6yWsg5PCVnday4ZzY
    callback: http://localhost:8080/auth/callback
    scopes: email profile openid

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
